CHANNEL_TO_URL = {
    "Адыгея": "",
    "Алтайский край": "https://t.me/+JI19fu_VwQI1MjAy",
    "Алтай (Республика Алтай)": "https://t.me/+JI19fu_VwQI1MjAy",
    "Амурская область": "",
    "Архангельская область": "https://t.me/+lRWhYMj5pws5MDky",
    "Астраханская область": "https://t.me/+Ra1BqcvH1OE4YjQy",
    "Башкортостан": "https://t.me/+GKdU3QmF-NE2YmEy",
    "Белгородская область": "https://t.me/+KmYWHn04-d1hNGI6",
    "Брянская область": "https://t.me/+IoG5owUBAR5hNGFi",
    "Бурятия": "",
    "Владимирская область": "https://t.me/+hHf1XTj5dJ5mNGEy",
    "Волгоградская область": "https://t.me/sbervolgograd",
    "Вологодская область": "https://t.me/+bQs2AIeZ09MwOTMy",
    "Воронежская область": "https://t.me/+XecQ7H_TUSJlNjYy",
    "Дагестан": "https://t.me/+jbAsqaTT6I5iZTky",
    "Еврейская автономная область": "",
    "Забайкальский край": "https://t.me/+NtJNR6GIUB00Yjcy",
    "Ивановская область": "",
    "Ингушетия": "",
    "Иркутская область": "https://t.me/+bOqhYr3FuXlmNzY6",
    "Кабардино-Балкария": "https://t.me/+yzHqoHKTuLViN2Vi",
    "Калининградская область": "https://t.me/+oJLIqHaGDCpkYjU6",
    "Калмыкия": "https://t.me/+CLV08X9FXC4yMDg6",
    "Калужская область": "https://t.me/kalugachat_SberStudent_SberZ",
    "Камчатский край": "",
    "Карачаево-Черкессия": "",
    "Карелия": "https://t.me/+BqJTP54kOellN2Qy",
    "Кемеровская область": "https://t.me/+kt2tmmqa-_tlNTdi",
    "Кировская область": "https://t.me/+cEY3VCdm2DBiZGI6",
    "Коми": "https://t.me/+baZ8Bjve4yc5M2Ri",
    "Костромская область": "",
    "Курганская область": "",
    "Курская область": "https://t.me/+MV-eVk8lLZE4MTgy",
    "Краснодарский край": "https://t.me/+ik49uwaJ6W9mMmIy",
    "Красноярский край": "https://t.me/+x9QuwH2oH5QwOTUy",
    "Крым": "https://t.me/+gbj13cMb0F05MmUy",
    "Липецкая область": "https://t.me/+jR51H5l0ud05YmRi",
    "Марий Эл": "https://t.me/+C04mLbnANYs5MTBi",
    "Магаданская область": "https://t.me/+yDy2AGZygMhmNzZi",
    "Мордовия": "https://t.me/+77d6_fg2fIJlOTBi",
    "Москва и Московская область": "https://t.me/+ku7DMiPs8ZNjYTYy",
    "Мурманская область": "",
    "Ненецкий автономный округ": "",
    "Нижегородская область": "https://t.me/+NgTdF4UbvYNhYTRi",
    "Новгородская область": "https://t.me/vn_sber",
    "Новосибирская область": "https://t.me/+-dj1qxmUpv4xYTcy",
    "Омская область": "https://t.me/+4wJ-HPU5KqMyNGYy",
    "Оренбургская область": "",
    "Орловская область": "",
    "Пензенская область": "https://t.me/+lILZ7uY7bwAyZGYy",
    "Пермский край": "https://t.me/+bycVBFim8TNlOTdi",
    "Приморский край": "https://t.me/+2MAetE0nM10yYzky",
    "Псковская область": "",
    "Ростовская область": "https://t.me/+FE0PIcEVLBA2YjJi",
    "Рязанская область": "",
    "Самарская область": "https://t.me/+0vavZATFiIgxYTRi",
    "Санкт-Петербург и Ленинградская область": "https://t.me/+SRK9_oX2olJlOWFi",
    "Саратовская область": "https://t.me/+yNnzvJtb6L0wMzhi",
    "Сахалинская область": "https://t.me/+MiW7hII16FdkYTJi",
    "Свердловская область": "https://t.me/+FweZ6NR34Y1jOTJi",
    "Севастополь": "https://t.me/sev_sber",
    "Северная Осетия (Алания)": "https://t.me/+xfEBcvbPEAw3ZDQy",
    "СКФО (укрупнённый чат)": "https://t.me/+jNC6qa6sjcI5Yjdi",
    "Смоленская область": "",
    "Ставропольский край": "https://t.me/+D4984dm180dmODU6",
    "Тамбовская область": "https://t.me/+-gAKIuIoeBNmZTAy",
    "Татарстан": "https://t.me/+qOEfOFHwcJgwNjIy",
    "Тверская область": "https://t.me/+i6dqGoCFqXNjODcy",
    "Томская область": "https://t.me/+xhtQOgezfH45OTYy",
    "Тульская область": "https://t.me/+eo2xZQoKriwwOTVi",
    "Тюменская область": "https://t.me/+6NND73P_Jf8xYjgy",
    "Тыва": "",
    "Удмуртия":  "https://t.me/+fhGUfVDQ8RU2YTBi",
    "Ульяновская область": "https://t.me/+vTMESWI7pZo4YzRi",
    "Хабаровский край": "https://t.me/+qgNBdfJKhIA0NmE6",
    "Хакасия": "",
    "Ханты-Мансийский автономный округ": "https://t.me/+EVZgjyr9MIVkMDBi",
    "Челябинская область": "https://t.me/+LAk8c2NxMnNjMWEy",
    "Челябинская область (Магнитогорск)": "https://t.me/+Ky5opUyYXUxmZDNi",
    "Чечня": "",
    "Чувашия": "https://t.me/+6t6fu0tGg201M2Uy",
    "Чукотка": "",
    "Якутия": "https://t.me/+XUVqcFS0djZkYzky",
    "Ямал": "",
    "Ярославская область": "https://t.me/+2gzQ9qMiw_MyNjEy"
}
